### ISSUE TITLE
Thrown exit code related errors are unclear

### ISSUE THREAD

**Issue by nicolasvahidzein** [point-source/dart_ping#4]
i am using your demo code and i get this error:

```
I/flutter (18135): PingData(response:null, summary:PingSummary(transmitted:5, received:0, time:4032 ms), error:null)
E/flutter (18135): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: Ping process exited with code: 1
[38;5;248mE/flutter (18135): #0      PingLinux.onListen.<anonymous closure> (package:dart_ping/src/ping/linux_ping.dart:47:11)[39;49m
[38;5;244mE/flutter (18135): #1      _rootRunUnary (dart:async/zone.dart:1198:47)[39;49m
[38;5;244mE/flutter (18135): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)[39;49m
[38;5;244mE/flutter (18135): #3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)[39;49m
[38;5;244mE/flutter (18135): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)[39;49m
[38;5;244mE/flutter (18135): #5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)[39;49m
[38;5;244mE/flutter (18135): #6      Future._completeWithValue (dart:async/future_impl.dart:529:5)[39;49m
[38;5;244mE/flutter (18135): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)[39;49m
[38;5;244mE/flutter (18135): #8      _rootRun (dart:async/zone.dart:1190:13)[39;49m
[38;5;244mE/flutter (18135): #9      _CustomZone.run (dart:async/zone.dart:1093:19)[39;49m
[38;5;244mE/flutter (18135): #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)[39;49m
[38;5;244mE/flutter (18135): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)[39;49m
[38;5;244mE/flutter (18135): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)[39;49m
[38;5;244mE/flutter (18135): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)[39;49m
```

**Comment by nicolasvahidzein** [comment]
By the way, i get this only when the endpoint i am trying to ping is not responding or is non-existing. How can i avoid this situation? Thanks

**Comment by nicolasvahidzein** [comment]
i am on v 3.0.0 btw because my app is not able to handle the newest version (4.0.2).

**Comment by point-source** [comment]
Thanks for the info and stacktrace. Are you on Linux or Android?

**Comment by nicolasvahidzein** [comment]
Android dear sir. 

_________________________________
Nicolas Zein
 
***@***.***
(+242) 06-602-02-37

On Apr 6, 2021, at 18:10, PointSource ***@***.***> wrote:

﻿
Thanks for the info and stacktrace. Are you on Linux or Android?

**Comment by point-source** [comment]
I think I've located the issue. Will try and get this fixed today

**Comment by nicolasvahidzein** [comment]
Thank you for support. I really appreciate it. 

_________________________________
Nicolas Zein
 
***@***.***
(+242) 06-602-02-37

On Apr 6, 2021, at 20:31, PointSource ***@***.***> wrote:

﻿
I think I've located the issue. Will try and get this fixed today

**Comment by point-source** [comment]
Alright, so this issue actually prompted me to refactor quite a bit of the code in order to make it smaller, more efficient, and fix some race conditions. I just pushed version 5.0.0 and it should hopefully fix this. 

That said, it is still a nullsafe release. Am I correct in assuming you are using version 3.0.0 because you haven't migrated to nullsafety yet? The code changes between 3.x and 5.x are non-trivial so I just want to make sure that [running mixed mode](https://dart.dev/null-safety/unsound-null-safety) is not an option for you before I try to backport these changes.

**Comment by nicolasvahidzein** [comment]
Oh man. I feel bad for making you do all this work. I cant migrate yet. Its a huge project and i don’t have the time just yet. I get this error because one of the domains is down or not pingable and either the stop or delay (Not sure who is the culprit) bugs otherwise its fine. Maybe you have a simple workaround that could work?

Thanks a lot.

**Comment by point-source** [comment]
Understood. I'll see what I can do. Note that you don't actually need to use a delay or a stop. That's just part of the example so people understand how to use it if they have to.

You can just create a new Ping instance with a count parameter and it will automatically close itself once it has pinged enough times. Something like this:

`var result = await Ping('1.1.1.1', count: 3).stream.toList();`

Will await 3 pings to occur, then return the results as a list object. No stop() necessary.

**Comment by keinou** [comment]
I have the same problem here, I have the project in null safe and using the dart_ping version: ^ 5.0.0, but I still get the error:

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Exception: Ping process exited with code: 1
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FormatException: Unexpected extension byte (at offset 2)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1887:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1362:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#11     _StreamController._add (dart:async/stream_controller.dart:607:7)
#12     _StreamController.add (dart:async/stream_controller.dart:554:5)
#13     _rootRunUnary (dart:async/zone.dart:1362:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#18     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#19     _StreamController._add (dart:async/stream_controller.dart:607:7)
#20     _StreamController.add (dart:async/stream_controller.dart:554:5)
#21     _Socket._onData (dart:io-patch/socket_patch.dart:2144:41)
#22     _rootRunUnary (dart:async/zone.dart:1370:13)
#23     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#27     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#28     _StreamController._add (dart:async/stream_controller.dart:607:7)
#29     _StreamController.add (dart:async/stream_controller.dart:554:5)
#30     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1680:33)
#31     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1192:14)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by point-source** [comment]
@keinou which perform are you on?

**Comment by keinou** [comment]
windows

**Comment by point-source** [comment]
@keinou technically, that is correct behavior since the exit code was > 0. Unfortunately, windows is not very specific about these exit codes and their meaning. Basically, 0 means the process ran without error, 1 means there was an error. As a result, dart_ping throws an error. 

That said, I can see how that behavior may not be ideal so I have published 5.1.0 which will only throw errors on windows if dart_ping itself fails. If the underlying ping process fails, a PingError object will be created and added to the PingSummary output. Hopefully you find this easier to work with.
